version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/www
    ports:
      - "8080:8000"
