version: "3"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: "sso"
    restart: always
    command: >
      sh -c "python manage.py migrate
      && gunicorn --bind 0.0.0.0:8080 --timeout 300 mulheresguerreiras.wsgi"
    ports:
      - "8080:8080"
    volumes:
      - ./static:/static
    networks:
      - app-network

  nginx:
    build: .docker/nginx
    container_name: "nginx"
    restart: always
    tty: true
#    entrypoint: dockerize -wait http://app:8080/healthcheck -timeout 20s nginx -g 'daemon off;'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static:/static
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
